{"message":"Cought exception","stack":"Error: Cought exception\n    at Object.<anonymous> (/Users/giridharr/Documents/code-with-mosh/backend/nodejs-course/vidly-be/index.js:59:7)\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\n    at Module.load (node:internal/modules/cjs/loader:998:32)\n    at Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","level":"error","timestamp":"2023-06-20T17:02:32.948Z"}
